name: Rebase on Upstream

on:
  schedule:
  - cron: "*/10 * * * *"  # every 5 minutes
  workflow_dispatch:    # run manually

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
        persist-credentials: false
    - uses: okazunori2013/rebase-upstream-action@master
      with:
        token: ${{ secrets.REBASE }}
